version: "3.8"

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    image: django-vue-nginx:latest
    #env_file: web/.env.local
    deploy:
      mode: global
      resources:
        limits:
          cpus: "2.0"
          memory: 32M
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - "traefik.constraint-label=traefik-public"
        - "traefik.http.routers.${STACK_NAME}-http.rule=Host(`${TRAEFIK_HOST}`)"
        - "traefik.http.routers.${STACK_NAME}-http.entrypoints=http"
        - "traefik.http.routers.${STACK_NAME}-http.middlewares=${STACK_NAME}-http-redirect"
        - "traefik.http.middlewares.${STACK_NAME}-http-redirect.redirectscheme.scheme=https"
        - "traefik.http.middlewares.${STACK_NAME}-http-redirect.redirectscheme.permanent=true"
        - "traefik.http.routers.${STACK_NAME}-https.rule=Host(`${TRAEFIK_HOST}`)"
        - "traefik.http.routers.${STACK_NAME}-https.entrypoints=https"
        - "traefik.http.routers.${STACK_NAME}-https.tls=true"
        - "traefik.http.services.${STACK_NAME}.loadbalancer.server.port=80"
        - "traefik.http.services.${STACK_NAME}.loadbalancer.server.scheme=http"
    healthcheck:
      test: ["CMD-SHELL", "curl -sf localhost:80/health-check/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      - app
    ports:
      - "${PORT:-80}:80"

  app:
    build:
      context: app
      dockerfile: Dockerfile
    image: django-vue-app:latest
    env_file: web/.env.local
    environment:
      DOCKER: true
    command: "gunicorn project.wsgi:application -b 0.0.0.0:9000 -w 2"
    deploy:
      mode: global
      resources:
        limits:
          cpus: "2.0"
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:9000/health-check/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
